{{/*
  
  Copyright 2026 The OKDP Authors.
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

*/}}

{{- $root := . }}
{{- $groupNames := sortAlpha (keys $root.Values.commands) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "okdp-examples.fullname" $root }}
  labels:
    {{- include "okdp-examples.labels" $root | nindent 4 }}
  {{- with $root.Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ $root.Values.job.backoffLimit | default 2 }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "okdp-examples.labels" $root | nindent 8 }}
          {{- with $root.Values.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
    spec:
      restartPolicy: {{ $root.Values.job.restartPolicy | default "Never" }}
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $root.Values.serviceAccount.create }}
      serviceAccountName: {{ include "okdp-examples.serviceAccountName" $root }}
      {{- end }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: runner
          securityContext:
            {{- toYaml $root.Values.securityContext | nindent 12 }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              
              echo "🚀 Starting OKDP Examples Job"
              {{- range $groupName := $groupNames }}
              echo ""
              echo "=================================================="
              echo "▶️ Running command: {{ $groupName }}"
              echo "=================================================="
              
              for script in /scripts/{{ $groupName }}__*.sh; do
                echo "➡️ Running step: $script"
                bash "$script"
              done
              
              echo "✅ Completed command: {{ $groupName }}"
              {{- end }}
              echo ""
              echo "🎉 ALL COMMANDS SUCCESSFULLY COMPLETED"

          {{- with $root.Values.extraEnvRaw }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            {{- with $root.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "okdp-examples.fullname" $root }}
        {{- with $root.Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}